before_script:
    - docker-php-ext-enable xdebug zip curl json

    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

# Select what we should cache between builds
cache:
    paths:
        - vendor/

variables:
    TIMEZONE: "UTC"
    MYSQL_DATABASE: mysql_database
    MYSQL_ROOT_PASSWORD: mysql_strong_password

# Run in the 5.6 image
php-5.6:
    image: tetraweb/php:5.6
    services:
        - mysql:5.6
    script:
        - vendor/bin/phpcs
        - vendor/bin/phpunit

# Run in the 7.0 image
php-7.0:
    image: tetraweb/php:7.0
    services:
        - mysql:5.6
    script:
        - vendor/bin/phpcs
        - vendor/bin/phpunit

# Run in the 7.1 image
php-7.1:
    image: tetraweb/php:7.1
    services:
        - mysql:5.6
    script:
        - vendor/bin/phpcs
        - vendor/bin/phpunit


